name: Prettier Action

on:
  push:
    branches: ["sburchfield33-juliazel-githubactions"]
  pull_request:
    branches: ["sburchfield33-juliazel-githubactions"]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with: 
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: "--write **/*.tsx"
          prettier_plugins: "prettier-plugin-tailwindcss"
          only_changed: True
